<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageVersion Include="Azure.Identity" Version="1.21.0" />
    <PackageVersion Include="Microsoft.Agents.AI.Foundry.Hosting" Version="1.17.0-preview.260804.1" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="ModelContextProtocol" Version="1.2.0" />
    <PackageVersion Include="Microsoft.Agents.AI.Mcp" Version="1.17.0-alpha.260804.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Foundry" Version="1.17.0-preview.260804.1" />
  </ItemGroup>
</Project>